---
- name: configuring apache
  hosts: all 
  tasks:  
  - name: install the packages
    yum: 
     name: httpd
     state: present 

  - name: copying a file
    copy: 
     src: index.html
     dest: /var/www/html/

  - name: start the service
    service: 
     name: httpd
     state: started 
