---
- name: running date and cal 
  hosts: webserver
  tasks: 
  - name: running date command
    shell: date
  - name: running cal command
    shell: cal 
  - name: creating directory
    file: 
     path: /root/ansible
     state: directory
